// <auto-generated />
using System;
using DatabaseSetupLocal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseSetupLocal.Migrations
{
    [DbContext(typeof(ShotsContext))]
    [Migration("20230109183720_ShotTableChange5")]
    partial class ShotTableChange5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabaseSetupLocal.Models.Shots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Driver")
                        .HasColumnType("longtext");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int?>("ShotsModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShotsModelId");

                    b.ToTable("Shots");
                });

            modelBuilder.Entity("DatabaseSetupLocal.Models.ShotsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PolePosition")
                        .HasColumnType("longtext");

                    b.Property<int>("RaceNo")
                        .HasColumnType("int");

                    b.Property<string>("Rand")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShotsModel");
                });

            modelBuilder.Entity("DatabaseSetupLocal.Models.Shots", b =>
                {
                    b.HasOne("DatabaseSetupLocal.Models.ShotsModel", null)
                        .WithMany("Shots")
                        .HasForeignKey("ShotsModelId");
                });

            modelBuilder.Entity("DatabaseSetupLocal.Models.ShotsModel", b =>
                {
                    b.Navigation("Shots");
                });
#pragma warning restore 612, 618
        }
    }
}
